# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isOwnedByCurrentUser',
            field=models.BooleanField(default=True),
        ),
    ]
